using System;
using System.Collections.Generic;
using System.Windows;
using System.Windows.Controls;

namespace AuthorizationApp
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            InitializeComponent();
        }

        private void OkButton_Click(object sender, RoutedEventArgs e)
        {
            string login = this.loginTxtBox.Text;
            string pass = this.passBox.Password;
            bool success = DBManager.AreKeyValueExistInDB(login, pass);
            
            if (success)
            {
                HideAllUIElements();
                ShowAuthInfo();            
            }
            else
            {
                MessageBox.Show("You typed wrong login/pass pair. Try again");
            }
        }

        private void registerButton_Click(object sender, RoutedEventArgs e)
        {
            RegisterWindow regWindow = new RegisterWindow();
            regWindow.Show(this);
            this.Hide();
        }

        private void ShowAuthInfo()
        {
            titleLabel.Visibility = Visibility.Visible;
            titleLabel.Content = "You are authorized. Now you can see this info:";
            List<User> users = DBManager.GetAllUsers();
            DataGrid dataGrid = new DataGrid();
            dataGrid.AutoGenerateColumns = true;
            dataGrid.ItemsSource = users;
            dataGrid.AutoGeneratedColumns += ConfigurateColumns;
            MainGrid.Children.Add(dataGrid);
        }

        private void ConfigurateColumns(object sender, EventArgs e)
        {
            var dataGrid = sender as DataGrid;
            foreach (var column in dataGrid.Columns)
            {
                column.Width = 100;
            }
            dataGrid.Columns[0].Visibility = Visibility.Collapsed;
            dataGrid.Columns[1].Header = "Логин";
            dataGrid.Columns[2].Header = "Пароль";
            dataGrid.Columns[3].Header = "Фамилия";
        }

        private void HideAllUIElements()
        {
            foreach (var child in MainGrid.Children)
            {
                (child as Control).Visibility = Visibility.Collapsed;
            }
        }
    }
}
